#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  4 23:02:50 2023

@author: flarnrules
"""

pi = 3.14159
radius = 2.2

# area of a circle
area = pi * (radius**2)
radius = radius + 1

# could also increment like this
# radius += 1